import { hasHeaderInjection } from "./testSendPolicy";

/**
 * The QA email allowlist (ADR-0027).
 *
 * A SEPARATE safety mechanism from the SAFE TEST hard-lock, deliberately. SAFE TEST
 * still reaches exactly one address and its policy is untouched; this path reaches
 * exactly FOUR, and neither can reach the other's addresses because neither knows
 * about the other's constants.
 *
 * The audience is UNREPRESENTABLE rather than merely validated, exactly as in
 * ADR-0013/0025: `QaMessage` has no `from`, `cc`, `bcc` or `replyTo` field, and `to`
 * is a single string chosen from a closed set. There is no shape in which a caller
 * could express a fifth recipient.
 *
 * The allowlist is a hard-coded constant. It is NEVER derived from — and this file
 * imports nothing from — Monday, the CRM projection, `CommunicationAddress`,
 * `Segment`, `CampaignRecipient`, or any audience. A test asserts that against the
 * source, because "we would never" is not a control.
 *
 * Pure: no I/O, no framework imports.
 */

/**
 * The ONLY four addresses a QA email may reach.
 *
 * Exact string equality after lower-casing and trimming. No alias expansion, no
 * plus-address variants, no display-name form, no domain wildcard.
 */
export const QA_ALLOWED_RECIPIENTS = [
  "khaled-s@axis-gps.com",
  "moaawya@axis-gps.com",
  "info@axis-gps.com",
  "saja@axis-gps.com",
] as const;

export type QaRecipient = (typeof QA_ALLOWED_RECIPIENTS)[number];

/** Frozen set for O(1) membership. Never mutated, never extended at runtime. */
const ALLOWED = new Set<string>(QA_ALLOWED_RECIPIENTS);

/**
 * Every QA subject begins with this, so a recipient can tell from the inbox list
 * alone that the message is an internal platform test and not a customer newsletter.
 */
export const QA_SUBJECT_PREFIX = "[AXIS Newsletter Platform TEST]" as const;

/** Applied exactly once — re-rendering must never produce a doubled prefix. */
export function applyQaSubjectPrefix(subject: string): string {
  const trimmed = subject.trim();
  if (trimmed.startsWith(QA_SUBJECT_PREFIX)) return trimmed;
  return `${QA_SUBJECT_PREFIX} ${trimmed}`;
}

export function hasQaSubjectPrefix(subject: string): boolean {
  return subject.trimStart().startsWith(QA_SUBJECT_PREFIX);
}

// ---------------------------------------------------------------------------
// The in-body testing notice
// ---------------------------------------------------------------------------

/**
 * The notice shown at the top of a QA message, per language.
 *
 * QA ONLY. The production newsletter template renders this only when a document
 * explicitly carries it, and no production code path sets it — asserted by test.
 */
export const QA_NOTICE: Record<"EN" | "HE" | "AR", string> = {
  EN: "This is a test email generated by the AXIS Newsletter Platform. No action is required.",
  HE: "זהו מייל בדיקה שנשלח ממערכת הניוזלטר של AXIS. אין צורך לבצע פעולה.",
  AR: "هذه رسالة اختبار تم إرسالها من منصة النشرات البريدية الخاصة بـ AXIS. لا يلزم اتخاذ أي إجراء.",
};

/** The notice matching a newsletter's language; English for `UNKNOWN`. */
export function qaNoticeFor(language: string): string {
  if (language === "HE") return QA_NOTICE.HE;
  if (language === "AR") return QA_NOTICE.AR;
  return QA_NOTICE.EN;
}

// ---------------------------------------------------------------------------
// The envelope gate
// ---------------------------------------------------------------------------

export type QaEnvelopeRejection =
  | "NOT_ALLOWED_RECIPIENT"
  | "MULTIPLE_RECIPIENTS"
  | "COPY_RECIPIENTS_FORBIDDEN"
  | "HEADER_INJECTION"
  | "NOT_A_STRING"
  | "DISPLAY_NAME_FORM"
  | "PLUS_ALIAS"
  | "MISSING_SUBJECT_PREFIX";

export const QA_ENVELOPE_MESSAGE: Record<QaEnvelopeRejection, string> = {
  NOT_ALLOWED_RECIPIENT:
    "That address is not on the QA list. QA email can only be sent to the four approved AXIS addresses.",
  MULTIPLE_RECIPIENTS: "A QA email has exactly one recipient.",
  COPY_RECIPIENTS_FORBIDDEN: "A QA email cannot carry CC or BCC recipients.",
  HEADER_INJECTION: "That address contains characters that are not allowed.",
  NOT_A_STRING: "That is not an email address.",
  DISPLAY_NAME_FORM:
    "Enter the address on its own — a display name such as \"Name <address>\" is not accepted.",
  PLUS_ALIAS:
    "Plus-address variants are not on the QA list. Use the exact approved address.",
  MISSING_SUBJECT_PREFIX: `A QA email subject must begin with ${QA_SUBJECT_PREFIX}.`,
};

export class UnsafeQaEnvelopeError extends Error {
  readonly reason: QaEnvelopeRejection;

  constructor(reason: QaEnvelopeRejection) {
    super(QA_ENVELOPE_MESSAGE[reason]);
    this.name = "UnsafeQaEnvelopeError";
    this.reason = reason;
  }
}

export function isAllowedQaRecipient(address: unknown): address is QaRecipient {
  return typeof address === "string" && ALLOWED.has(address.trim().toLowerCase());
}

/**
 * Anything that could widen a QA message's audience.
 *
 * Accepts `unknown` deliberately: this is the last gate before the network, so it must
 * be able to refuse a shape the type system was told could not exist.
 */
export interface QaEnvelopeCandidate {
  to: unknown;
  cc?: unknown;
  bcc?: unknown;
  subject?: unknown;
}

/**
 * The gate. REFUSES rather than repairs.
 *
 * A caller-supplied `cc` is not quietly dropped, a display-name wrapper is not parsed
 * down to its address, and a plus-alias is not normalised to its base — every one of
 * those is a rejection, because a caller that supplied one has misunderstood something
 * and the safe response is to stop rather than to guess what they meant.
 *
 * Returns the address in canonical allowlist form, NOT the caller's string, so a
 * homoglyph or a stray character cannot survive the gate.
 */
export function assertSafeQaEnvelope(candidate: QaEnvelopeCandidate): QaRecipient {
  if (candidate.cc !== undefined || candidate.bcc !== undefined) {
    throw new UnsafeQaEnvelopeError("COPY_RECIPIENTS_FORBIDDEN");
  }
  if (Array.isArray(candidate.to)) {
    throw new UnsafeQaEnvelopeError("MULTIPLE_RECIPIENTS");
  }
  if (typeof candidate.to !== "string") {
    // null, undefined, numbers, objects — anything that is not a plain string.
    throw new UnsafeQaEnvelopeError("NOT_A_STRING");
  }

  // Checked on the RAW value, before trimming: trimming a trailing newline first
  // would hide the very injection this is looking for.
  if (hasHeaderInjection(candidate.to)) {
    throw new UnsafeQaEnvelopeError("HEADER_INJECTION");
  }

  const raw = candidate.to.trim();
  if (raw === "") throw new UnsafeQaEnvelopeError("NOT_A_STRING");

  // A comma or semicolon is a second recipient smuggled into one string.
  if (raw.includes(",") || raw.includes(";")) {
    throw new UnsafeQaEnvelopeError("MULTIPLE_RECIPIENTS");
  }
  // `Name <addr>` — refused outright rather than unwrapped.
  if (raw.includes("<") || raw.includes(">")) {
    throw new UnsafeQaEnvelopeError("DISPLAY_NAME_FORM");
  }
  // Reported specifically, because `khaled-s+qa@axis-gps.com` delivers to a real
  // mailbox and would otherwise look like a harmless variation of an approved address.
  if (raw.includes("+")) {
    throw new UnsafeQaEnvelopeError("PLUS_ALIAS");
  }

  if (!isAllowedQaRecipient(raw)) {
    throw new UnsafeQaEnvelopeError("NOT_ALLOWED_RECIPIENT");
  }

  if (candidate.subject !== undefined) {
    if (typeof candidate.subject !== "string" || !hasQaSubjectPrefix(candidate.subject)) {
      throw new UnsafeQaEnvelopeError("MISSING_SUBJECT_PREFIX");
    }
    if (hasHeaderInjection(candidate.subject)) {
      throw new UnsafeQaEnvelopeError("HEADER_INJECTION");
    }
  }

  // The CONSTANT, never the caller's string.
  const canonical = QA_ALLOWED_RECIPIENTS.find(
    (allowed) => allowed === raw.toLowerCase(),
  );
  if (!canonical) throw new UnsafeQaEnvelopeError("NOT_ALLOWED_RECIPIENT");
  return canonical;
}

// ---------------------------------------------------------------------------
// Availability
// ---------------------------------------------------------------------------

export type QaBlocker =
  | "QA_MODE_OFF"
  | "TRANSPORT_NOT_CONFIGURED"
  | "NO_CONTENT"
  | "CAP_REACHED"
  | "NO_OPEN_RUN";

export const QA_BLOCKER_MESSAGE: Record<QaBlocker, string> = {
  QA_MODE_OFF:
    "QA email is switched off. Set QA_EMAIL_ENABLED=true in .env.local and restart the server.",
  TRANSPORT_NOT_CONFIGURED:
    "The QA email transport is not configured, so nothing can be sent.",
  NO_CONTENT: "This QA scenario has no content to render.",
  CAP_REACHED:
    "The QA send cap for this recipient has been reached. No further QA email will be sent.",
  NO_OPEN_RUN:
    "No QA run is open. An administrator must start one deliberately — a run is never opened by a restart, a test, or an environment change.",
};

/**
 * Caps, enforced server-side.
 *
 * These are a safety limit, not a target. Exceeding them is refused rather than
 * warned about — a runaway loop that mails a colleague forty times is exactly what a
 * hard stop is for.
 */
export const QA_RECOMMENDED_TOTAL = 32;
export const QA_HARD_TOTAL = 40;
export const QA_HARD_PER_RECIPIENT = 10;

export interface QaCapState {
  totalSent: number;
  sentToRecipient: number;
}

export function isWithinQaCaps(state: QaCapState): boolean {
  return (
    state.totalSent < QA_HARD_TOTAL &&
    state.sentToRecipient < QA_HARD_PER_RECIPIENT
  );
}
