import Link from "next/link";
import { Capability, requirePageCapability } from "../../server/auth/session";
import { getJobOperations } from "../../server/services/jobService";
import { CrmScheduleControl, RetryCrmControl } from "../../ui/OperationsControls";
import { Badge, Card, PageHeader, buttonSecondary } from "../../ui/primitives";
export const dynamic = "force-dynamic";
const stateLabels: Record<string, string> = { PENDING: "Waiting", RUNNING: "Running", SUCCEEDED: "Completed", FAILED: "Failed", ATTENTION: "Needs attention", CANCELED: "Canceled" };
const kindLabels: Record<string, string> = { CRM_SYNC: "CRM reconciliation", AUTOMATION: "Prepare newsletter draft", DISPATCH: "Customer delivery" };
const problems: Record<string,string> = { WORKER_INTERRUPTED: "Execution was interrupted. Review the result before continuing.",
  UNCERTAIN_SUBMISSION: "Provider acceptance is uncertain. Review the report and provider evidence; these addresses will not be retried.",
  SCHEDULE_PAUSED_OR_CHANGED: "The schedule was paused or its authorization changed.", EXECUTION_FAILED: "Execution failed. Check the related workflow and its configuration.",
  BLOCKED: "Delivery checks require attention. Open the newsletter to review them.", DISABLED: "Customer delivery is disabled." };
export default async function OperationsPage() {
  await requirePageCapability(Capability.RUN_CRM_SYNC, "/operations");
  const data = await getJobOperations();
  const active = data.schedulerActive;
  const attention = data.jobs.filter(job => job.state === "ATTENTION" || job.state === "FAILED").length;
  return <>
    <PageHeader title="Operations" description="Scheduled work, CRM updates and delivery execution in one place." actions={<Link href="/operations" className={buttonSecondary}>Refresh status</Link>}/>
    <div className="grid gap-4 md:grid-cols-3"><Card className="p-5"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Scheduler</p><div className="mt-4"><Badge tone={active ? "success" : "warning"}>{active ? "Checking for work" : data.schedulerEnabled ? "Heartbeat missing" : "Disabled on server"}</Badge></div><p className="mt-3 text-xs text-slate-500">{data.heartbeat ? `Last check: ${data.heartbeat.lastTickAt.toISOString().replace("T", " ").slice(0,19)} UTC` : "No scheduler heartbeat recorded."}</p></Card>
      <Card className="p-5"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Needs attention</p><p className="mt-3 text-4xl font-semibold tabular-nums">{attention}</p><p className="mt-3 text-xs text-slate-500">Among the latest 100 jobs</p></Card>
      <Card className="p-5"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Monday notifications</p><div className="mt-4"><Badge tone={data.mondayWebhookEnabled ? "info" : "neutral"}>{data.mondayWebhookEnabled ? "Signed intake enabled" : "Intake disabled"}</Badge></div><p className="mt-3 text-xs text-slate-500">{data.webhookCounts.reduce((sum,row) => sum + (row.status === "QUEUED" ? row._count._all : 0),0)} notifications waiting for reconciliation</p></Card></div>
    <div className="my-6 grid gap-6 lg:grid-cols-2"><Card className="p-6"><h2 className="font-semibold">Keep the CRM projection current</h2><p className="mt-2 text-sm text-slate-500">Periodic sync repairs missed notifications. Signed Monday events coalesce into a single reconciliation for each minute.</p><CrmScheduleControl enabled={data.schedule?.isEnabled ?? false} interval={data.schedule?.intervalMinutes ?? 60}/></Card>
      <Card className="p-6"><h2 className="font-semibold">Scheduled communication</h2><p className="mt-2 text-sm leading-relaxed text-slate-500">Automations prepare drafts from reviewed content. Customer delivery follows a separate approved audience and an explicit time. Missed delivery windows and uncertain provider outcomes require review.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/automations" className={buttonSecondary}>Manage automations</Link><Link href="/reports" className={buttonSecondary}>Delivery reports</Link></div></Card></div>
    <Card className="overflow-hidden"><div className="border-b border-slate-100 p-5"><h2 className="font-semibold">Recent jobs</h2><p className="mt-1 text-xs text-slate-500">Latest 100 jobs · timestamps in UTC</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{["Work", "Status", "Scheduled for", "Runs", "Next step"].map(label => <th key={label} className="px-5 py-3 text-start font-semibold">{label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{data.jobs.map(job => <tr key={job.id}><td className="px-5 py-4 font-medium">{kindLabels[job.kind]}</td><td className="px-5 py-4"><Badge tone={job.state === "SUCCEEDED" ? "success" : job.state === "ATTENTION" ? "warning" : "neutral"}>{stateLabels[job.state]}</Badge></td><td className="whitespace-nowrap px-5 py-4 text-xs text-slate-500">{job.scheduledFor.toISOString().slice(0,16).replace("T"," ")}</td><td className="px-5 py-4 tabular-nums">{job.attempts}</td><td className="max-w-sm px-5 py-4">{job.errorCode && <p className="mb-2 text-xs text-slate-500">{problems[job.errorCode] ?? "Open the related workflow to review its current checks."}</p>}{job.kind === "CRM_SYNC" && ["FAILED","ATTENTION"].includes(job.state) ? <RetryCrmControl id={job.id}/> : job.resourceId ? <Link className="text-xs font-semibold text-sky-700" href={job.kind === "DISPATCH" ? `/newsletters/${job.resourceId}/readiness` : `/automations/${job.resourceId}`}>Open workflow →</Link> : "—"}</td></tr>)}{!data.jobs.length && <tr><td colSpan={5} className="p-10 text-center text-slate-500">No background work recorded yet. Enable a schedule to begin.</td></tr>}</tbody></table></div></Card>
  </>;
}
